# Generated by Django 3.1.3 on 2022-04-29 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0002_auto_20220426_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedetails',
            name='gameID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopApp.gamelist'),
        ),
    ]
