# Generated by Django 3.1.3 on 2022-05-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0005_auto_20220501_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('uniqueid', models.IntegerField(primary_key=True, serialize=False)),
                ('customerID', models.CharField(max_length=20)),
                ('totalPrice', models.FloatField()),
                ('purchaseDate', models.DateField()),
                ('productList', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
