# Generated by Django 3.1.3 on 2022-05-04 13:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0006_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='customerEmail',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
